### ISSUE TITLE
Support for multiple google calendars

### ISSUE THREAD

**Issue by jeeftor** [jeeftor/alfredToday#1]
Eventually one day add some support for multiple calendars.

**Comment by jeeftor** [comment]
This is done in version 4 :)

**Comment by edasque** [comment]
But you can't have calendars from 2 or more Google Accounts, right?

**Comment by jeeftor** [comment]
If you share calendars from one account to another you can access them via "another"

**Comment by jeeftor** [comment]
I have 5 calendars in my google selection FYI
