### ISSUE TITLE
When trying to set up Google Calendar I receive "Error in workflow"

### ISSUE THREAD

**Issue by galligan** [jeeftor/alfredToday#10]
<img width="611" alt="screen shot 2017-01-28 at 8 45 48 am" src="https://cloud.githubusercontent.com/assets/25037981/22398135/4866e13e-e536-11e6-85f3-cf8af145e583.png">

See above screenshot.

**Comment by galligan** [comment]
This is using the 5.0.3 build.

**Comment by jeeftor** [comment]
Thought I fixed that.... the file client secret is in the wrong dir .... An easy fix is to copy the file to both the root and /src directories until I fix the bug. That should fix it

**Comment by jeeftor** [comment]
Try release 5.0.5 - that "should" fix things.

**Comment by galligan** [comment]
<img width="611" alt="screen shot 2017-01-28 at 10 26 08 am" src="https://cloud.githubusercontent.com/assets/25037981/22398809/3f2be778-e544-11e6-8e3d-7354df3d5dc1.png">

Thanks for the quick build! However when I try to run the command, it just acts as though I'm doing a search.

**Comment by jeeftor** [comment]
Well that's odd. Try tcreset? First. Otherwise I'll do a clean install on my end. Also can you check the log. Might have screwed something else. Don't have the best testing environment

**Comment by galligan** [comment]
Same result unfortunately!

On Sat, Jan 28, 2017 at 11:00 AM Jeef <notifications@github.com> wrote:

Well that's odd. Try tcreset? First. Otherwise I'll do a clean install on
my end. Also can you check the log. Might have screwed something else.
Don't have the best testing environment

Sent from my iPhone

> On Jan 28, 2017, at 1:27 PM, mg0716 <notifications@github.com> wrote:
>
>
> Thanks for the quick build! However when I try to run the command, it
just acts as though I'm doing a search.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jeeftor/alfredToday/issues/10#issuecomment-275867307>,
or mute the thread

**Comment by jeeftor** [comment]
Dbgtoday - openlog and paste the results or email them to me?

**Comment by galligan** [comment]
[2017-01-28 11:31:49][STDERR: input.scriptfilter] 11:31:49 settings.py:294
DEBUG           _____ _______________________   _____________
11:31:49 settings.py:295 DEBUG          / ___// ____/_  __/_  __/  _/ | / /
____/ ___/
11:31:49 settings.py:296 DEBUG          \__ \/ __/   / /   / /  / //  |/ /
/ __ \__ \
11:31:49 settings.py:297 DEBUG         ___/ / /___  / /   / / _/ // /|  /
/_/ /___/ /
11:31:49 settings.py:298 DEBUG        /____/_____/ /_/   /_/ /___/_/
|_/\____//____/
11:31:49 workflow.py:2156 DEBUG    Workflow version : 5.0.5
11:31:49 workflow.py:1568 DEBUG    Reading settings from
`/Users/mattgalligan/Library/Application Support/Alfred 3/Workflow
Data/org.jeef.today/settings.json` ...
11:31:49 workflow.py:2351 DEBUG    Set last run version : 5.0.5
11:31:49 workflow.py:2194 DEBUG    Workflow finished in 0.001 seconds.
[2017-01-28 11:31:51][ERROR: input.scriptfilter] Code 2: 11:31:51
workflow.py:2156 DEBUG    Workflow version : 5.0.5
11:31:51 workflow.py:1568 DEBUG    Reading settings from
`/Users/mattgalligan/Library/Application Support/Alfred 3/Workflow
Data/org.jeef.today/settings.json` ...
No handlers could be found for logger "oauth2client.util"
11:31:51 tools.py:301 DEBUG    Starting auth function
usage: calendar_settings.py [--auth_host_name AUTH_HOST_NAME]
                            [--noauth_local_webserver]
                            [--auth_host_port [AUTH_HOST_PORT
[AUTH_HOST_PORT ...]]]
                            [--logging_level
{DEBUG,INFO,WARNING,ERROR,CRITICAL}]
calendar_settings.py: error: unrecognized arguments: query
11:31:51 workflow.py:2194 DEBUG    Workflow finished in 0.005 seconds.

**Comment by jeeftor** [comment]
hmm.... so it looks like you are calling: `tcgc` which is where you select google calendars...

I just changed `"query"` to `"{query}"` in the Alfred command - lets see if that fixes anythings.  New release coming soon.

Which OS are you running out of curiosity?

**Comment by jeeftor** [comment]
Try new release: https://github.com/jeeftor/alfredToday/releases/tag/v5.0.6

maybe that will help?

**Comment by galligan** [comment]
Everything seems to be running as expected now! Thanks for all that.
