### ISSUE TITLE
Org.jeff.today

### ISSUE THREAD

**Issue by CordRush** [jeeftor/alfredToday#2]
Hey there,

When I type "Today" I keep getting this meesage (see below). What should I do? Can't wait to use this workflow. Thanks!
![screen shot 2016-09-14 at 7 50 27 am](https://cloud.githubusercontent.com/assets/8126271/18563089/1fa5f81c-7b3b-11e6-9a82-6a3d4f42e961.png)

**Comment by jeeftor** [comment]
Please try release v3.9.7

I was making a function that returned a `kwargs` however forgot to `**`.  If that means anything to you than you. 

I pushed a new release however:

https://github.com/jeeftor/alfredToday/releases/tag/v3.9.7

**Comment by CordRush** [comment]
Worked. Thanks man!
