### ISSUE TITLE
it's not working on my laptop

### ISSUE THREAD

**Issue by sdaza** [jeeftor/alfredToday#3]
Alfred 3. 

Starting debug for 'Today Menu'

[2016-09-18 12:05:43][ERROR: input.scriptfilter] Code 2: 12:05:43 workflow.py:2157 DEBUG    Workflow version : 2.0.1
12:05:43 workflow.py:1558 DEBUG    Reading settings from `/Users/sdaza/Library/Application Support/Alfred 3/Workflow Data/org.jeef.today/settings.json` ...
12:05:43 doubleQuery.py:17 INFO     Refreshing Data Cache [Google]
usage: doubleQuery.py [--auth_host_name AUTH_HOST_NAME]
                      [--noauth_local_webserver]
                      [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
                      [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
doubleQuery.py: error: unrecognized arguments: 0
12:05:43 workflow.py:2195 DEBUG    Workflow finished in 0.109 seconds.

**Comment by jeeftor** [comment]
I think you are running a very old version of the plugin. Could you try a newer release. 

The doublequery.py got renamed to today.py some versions ago. The current version is 4.1. Looks like you have v2.0.1

Try this build: https://github.com/jeeftor/alfredToday/releases/tag/v4.1.0
