### ISSUE TITLE
Ignore day+ events

### ISSUE THREAD

**Issue by califa** [jeeftor/alfredToday#6]
Hey, could this possibly be made to ignore day-long events?
They don't have much useful information and clog up the top of the list :)

Thanks!

![image](https://cloud.githubusercontent.com/assets/23412117/20580615/603e484c-b1a1-11e6-8fe3-6319cd845704.png)

**Comment by jeeftor** [comment]
I could put a config option prob. Will be able to work I about 2 weeks on it.

**Comment by califa** [comment]
Awesome, thanks! :)

**Comment by jeeftor** [comment]
Currently I aded this functionality for outlook - i'll see about doing it for Google Soon.

**Comment by jeeftor** [comment]
Fixed in the latest build https://github.com/jeeftor/alfredToday/releases/tag/v5.0.2
